# -*- coding: utf-8 -*-
"""180123015_harsh_q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PcHsLg73RTSCUeyNb0h_-MOPNuxQD1YB
"""

import random
import matplotlib.pyplot as plt
import math

def func(arg):
  switcher=[0.11,0.12,0.09,0.08,0.12,0.1,0.09,0.09,0.1,0.1]
  return switcher[arg-1]

def calc(no,c):
  hgg =no
  print("value of c is", c)
  print("size of generated sample", hgg)
  
  t=0
  sum=0
  h=0
  main=[]
  while t<hgg:
    h=h+1
    X=random.random()
    Y=random.random()
    if Y==0:
      Y=1
    Y=math.ceil(10*Y)
    if X<=func(Y)/(c*0.1):
      main.append(Y)
      t=t+1
  leng=len(main)
  u=[0,0,0,0,0,0,0,0,0,0]
  for i in range(leng):
    C=main[i]
    u[C-1]=u[C-1]+1
  for i in range(10):
    u[i]=u[i]/leng
  print("pmf of the random sample")
  print(u)
  print("avg no. of attempts required for acceptance", h/hgg)
  
  print("   ")

it=10000
while it<=1000000:
  calc(it,2)
  it=it*10

it=10000
while it<=1000000:
  calc(it,7)
  it=it*10