# -*- coding: utf-8 -*-
"""180123015_harsh_q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PcHsLg73RTSCUeyNb0h_-MOPNuxQD1YB
"""

import matplotlib.pyplot as plt
import math
import random

scape=[1000000, 10000, 100000, 6000000]
for hgg in scape:
 print(" ")
 print("sample size is", hgg)
 u=[0]
 u.pop(0)
 
 for i in range(hgg):
   b=random.random()
   if b<0:
     b=b+1
   u.append(b)
  
 gg=[0]
 for i in range(5000):
    gg.append(0)
 gg.pop(0)
 for i in range(len(u)):
    zz=math.ceil(5000*u[i])
    
    gg[zz-1]=gg[zz-1]+1
 ml=[1]
 for i in range(5000):
   gg[i]=gg[i]/len(u)
 print(gg)
 print("pmf of the Rv is printed above, they correspond to 1,3,5,7 ...")
 sum=0
 for i in range(5000):
   sum=sum+gg[i]
 print("Average pmf is ", sum/5000)
 print("                     *********      **********")